//
//  SpringModels.swift
//  SpringApp
//
//  Created by Alexey Efimov on 16.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import QuartzCore

typealias SpringRequest = Spring.Animate.Request
typealias SpringResponse = Spring.Animate.Response
typealias SpringViewModel = Spring.Animate.ViewModel

typealias TransformRequest = Spring.TransformSpringView.Request
typealias TransformResponse = Spring.TransformSpringView.Response
typealias TransformViewModel = Spring.TransformSpringView.ViewModel

enum Spring {
 
    // MARK: Animate Use case
    enum Animate {
        struct Request {
            var rowIndex = 0
            let autostart: Bool
            let autohide: Bool
            
            let title: String
            let curve: String
            
            var force: Double
            var delay: Double
            var duration: Double
            let damping: Double
            let velocity: Double
            let repeatCount: Float
            let x: Double
            let y: Double
            let scaleX: Double
            let scaleY: Double
            let scale: Double
            let rotate: Double
        }
        
        struct Response {
            let animation: Animation
            var animationList: [String] = []
            var curveList: [String] = []
        }
        
        struct ViewModel {
            let autostart: Bool
            let autohide: Bool
            
            let title: String
            let curve: String
            
            let force: Double
            let delay: Double
            let duration: Double
            let damping: Double
            let velocity: Double
            let repeatCount: Float
            let x: Double
            let y: Double
            let scaleX: Double
            let scaleY: Double
            let scale: Double
            let rotate: Double
            
            let forceText: String
            let durationText: String
            let delayText: String
            
            var animationList: [String] = []
            var curveList: [String] = []
            
            init(animation: Animation) {
                autostart = animation.autostart
                autohide = animation.autohide
                
                title = animation.title
                curve = animation.curve
                
                force = animation.force
                delay = animation.delay
                duration = animation.duration
                damping = animation.damping
                velocity = animation.velocity
                repeatCount = animation.repeatCount
                x = animation.x
                y = animation.y
                scaleX = animation.scaleX
                scaleY = animation.scaleY
                scale = animation.scale
                rotate = animation.rotate
                
                forceText = String(format: "Force: %.1f", animation.force)
                durationText = String(format: "Duration: %.1f", animation.duration)
                delayText = String(format: "Delay: %.1f", animation.delay)
            }
        }
        
    }
    
    // MARK: - Transform use case
    enum TransformSpringView {
        
        struct Request {
            var viewSize: Double = 0
        }
        
        struct Response {
            let keyPath: String
            let fromValue: Double
            let toValue: Double
            let duration: Double
        }
        
        struct ViewModel {
            let cornerRadius: Double
            let animation: CABasicAnimation
            let key: String
        }
    }
}
