//
//  SpringRouter.swift
//  SpringApp
//
//  Created by Alexey Efimov on 16.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SpringRoutingLogic {
    func routeToOptions(segue: UIStoryboardSegue?)
    func routeToCode()
}

protocol SpringDataPassing {
    var dataStore: SpringDataStore? { get }
}

class SpringRouter: NSObject, SpringRoutingLogic, SpringDataPassing {
    
    weak var springVC: SpringViewController?
    var dataStore: SpringDataStore?
    
    // MARK: Routing
    func routeToOptions(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! OptionsViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToOptions(source: dataStore!, destination: &destinationDS)
            destinationVC.delegate = springVC
            destinationDS.delegate = dataStore
        }
    }
    
    func routeToCode() {
        let destinationVC = CodeViewController()
        var destinationDS = destinationVC.router!.dataStore!
        passDataToCode(source: dataStore!, destination: &destinationDS)
        navigateToCode(source: springVC!, destination: destinationVC)
    }
    
    // MARK: Navigation
    private func navigateToOptions(source: SpringViewController, destination: OptionsViewController) {
        source.present(destination, animated: true)
    }
    
    private func navigateToCode(source: SpringViewController, destination: CodeViewController) {
        guard let sheetView = destination.sheetPresentationController else { return }
        sheetView.detents = [.medium()]
        source.present(destination, animated: false)
    }
    
    // MARK: Passing data
    private func passDataToOptions(source: SpringDataStore, destination: inout OptionsDataStore) {
        destination.animation = source.animation
    }
    
    private func passDataToCode(source: SpringDataStore, destination: inout CodeDataStore) {
        destination.animation = source.animation
    }
}
