//
//  OptionsModels.swift
//  SpringApp
//
//  Created by Alexey Efimov on 17.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

typealias OptionsRequest = Options.Animate.Request
typealias OptionsResponse = Options.Animate.Response
typealias OptionsViewModel = Options.Animate.ViewModel

enum Options {
 
    // MARK: Use cases
    enum Animate {
        struct Request {
            var rowIndex = 0
            var forceSliderValue: Float = 1
            var durationSliderValue: Float = 1
            var delaySliderValue: Float = 0
            var damping: Float = 0.7
            var velocity: Float = 0.7
            var rotate: Float = 0
            var x: Float = 0
            var y: Float = 0
            var scale: Float = 0
        }
        
        struct Response {
            let animation: Animation
        }
        
        struct ViewModel {
            let autostart: Bool
            let autohide: Bool
            
            let title: String
            let curve: String
            
            let force: Double
            let delay: Double
            let duration: Double
            let damping: Double
            let velocity: Double
            let repeatCount: Float
            let x: Double
            let y: Double
            let scaleX: Double
            let scaleY: Double
            let scale: Double
            let rotate: Double
            
            let forceText: String
            let durationText: String
            let delayText: String
            let dampingText: String
            let velocityText: String
            let scaleText: String
            let xText: String
            let yText: String
            let rotateText: String
        }
    }
}
