//
//  CodeRouter.swift
//  SpringApp
//
//  Created by Alexey Efimov on 18.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CodeRoutingLogic {
    
}

protocol CodeDataPassing {
    var dataStore: CodeDataStore? { get }
}

class CodeRouter: NSObject, CodeRoutingLogic, CodeDataPassing {
    weak var viewController: CodeViewController?
    var dataStore: CodeDataStore?
}
