//
//  CodePresenter.swift
//  SpringApp
//
//  Created by Alexey Efimov on 18.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CodePresentationLogic {
    func presentCode(response: CodeResponse)
}

class CodePresenter: CodePresentationLogic {
    
    weak var viewController: CodeDisplayLogic?
    
    func presentCode(response: CodeResponse) {
        var codeText = ""
        
        if !response.animation.title.isEmpty {
            codeText += "   view.animation = \"\(response.animation.title)\"\n"
        }
        if !response.animation.curve.isEmpty {
            codeText += "   view.curve = \"\(response.animation.curve)\"\n"
        }
        if response.animation.force != 1 {
            codeText += String(format: "\n   view.force = %.1f\n", response.animation.force)
        }
        if response.animation.duration != 0.7 {
            codeText += String(format: "   view.duration = %.1f\n", response.animation.duration)
        }
        if response.animation.delay != 0 {
            codeText += String(format: "   view.delay = %.1f\n", response.animation.delay)
        }
        if response.animation.damping != 0.7 {
            codeText += String(format: "   view.damping = %.1f\n", response.animation.damping)
        }
        if response.animation.velocity != 0.7 {
            codeText += String(format: "   view.velocity = %.1f\n", response.animation.velocity)
        }
        if response.animation.rotate != 0 {
            codeText += String(format: "   view.rotate = %.1f\n", response.animation.rotate)
        }
        if response.animation.x != 0 {
            codeText += String(format: "   view.x = %.1f\n", response.animation.x)
        }
        if response.animation.y != 0 {
            codeText += String(format: "   view.y = %.1f\n", response.animation.y)
        }
        if response.animation.scale != 1 {
            codeText += String(format: "   view.scale = %.1f\n", response.animation.scale)
        }
        codeText += "\n   view.animate()"
        let viewModel = CodeViewModel(codeText: codeText)
        viewController?.displayCode(viewModel: viewModel)
    }
}
