//
//  CodeModels.swift
//  SpringApp
//
//  Created by Alexey Efimov on 18.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

typealias CodeResponse = Code.PresentCode.Response
typealias CodeViewModel = Code.PresentCode.ViewModel

enum Code {
 
    // MARK: Use cases
    enum PresentCode {
        
        struct Response {
            let animation: Animation
        }
        
        struct ViewModel {
            let codeText: String
        }
    }
}
