//
//  CodeInteractor.swift
//  SpringApp
//
//  Created by Alexey Efimov on 18.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CodeBusinessLogic {
    func showCode()
}

protocol CodeDataStore {
    var animation: Animation? { get set }
}

class CodeInteractor: CodeBusinessLogic, CodeDataStore {
    
    var presenter: CodePresentationLogic?
    var animation: Animation?
    
    func showCode() {
        guard let animation = animation else { return }
        let response = CodeResponse(animation: animation)
        presenter?.presentCode(response: response)
    }
}
